name: Build App Bundle

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.0'  # Replace with your desired Flutter version

      - name: Configure environment variables
        run: |
          echo "KEYSTORE_PATH=$KEYSTORE_PATH" >> $GITHUB_ENV
          echo "KEYSTORE_PASSWORD=$KEYSTORE_PASSWORD" >> $GITHUB_ENV
          echo "KEY_ALIAS=$KEY_ALIAS" >> $GITHUB_ENV
          echo "KEY_PASSWORD=$KEY_PASSWORD" >> $GITHUB_ENV

      - name: Build app bundle
        run: flutter build appbundle --release

      # Add steps to handle the built app bundle, e.g., upload as artifact
      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: app-bundle
      #     path: build/app/outputs/bundle/release/*.aab
